/* ============================================================
   So'z O'rgatuvchi — Ma'lumotlar
   Fayl     : js/data.js
   Qamrab oladi:
     • WORD_TYPES  — ingliz so'zlarining grammatik turi lug'ati
     • TYPE_LABELS — qisqa tur kodlari ↔ to'liq nom
     • DEFAULT_UNITS — dastur ichiga o'rnatilgan so'z birliklari
                       (o'chirilsa localStorage'dan tiklanadi)
     • IRREGULAR_VERBS — 66 ta noto'g'ri fe'l (base/past/pp/uz/emoji)
   ============================================================ */

// ===== WORD TYPE =====
const WORD_TYPES={
  "boring":"adj","careful":"adj","clear":"adj","correct":"adj","disappointed":"adj",
  "good":"adj","great":"adj","heavy":"adj","poor":"adj","quiet":"adj","serious":"adj",
  "simple":"adj","slow":"adj","strong":"adj","virtual":"adj","worth":"adj",
  "carefully":"adv","clearly":"adv","correctly":"adv","dangerously":"adv","online":"adv",
  "quietly":"adv","slowly":"adv","well":"adv",
  "baker's":"n","butcher's":"n","button":"n","cash":"n","changing room":"n","coat":"n",
  "designer shoes":"n","dress":"n","gloves":"n","hat":"n","hoodie":"n","information":"n",
  "jacket":"n","jeans":"n","jewellery":"n","meat":"n","newsagent's":"n","postcard":"n",
  "rain water":"n","reading glasses":"n","receipt":"n","sales":"n","shopping centre":"n",
  "shorts":"n","skirt":"n","socks":"n","suit":"n","tie":"n","trainers":"n","trousers":"n",
  "t-shirt":"n","umbrella":"n","value":"n","vending machine":"n","wedding":"n",
  "recommend":"v","relax":"v","return":"v","spend":"v",
};
const TYPE_LABELS={"adj":"adjective","adv":"adverb","n":"noun","v":"verb"};
function getWordType(en){return WORD_TYPES[en?.toLowerCase().trim()]||null;}
function getTypeLabel(t){return TYPE_LABELS[t]||null;}

// ===== DATA =====
const DEFAULT_UNITS = [
{id:'u1',name:'Elementary Unit 1',words:[
{en:"American",tr:"/əˈmerɪkən/",uz:"amerikalik"},{en:"Arabic",tr:"/ˈærəbɪk/",uz:"arab millatiga mansub"},
{en:"artist",tr:"/ˈɑːtɪst/",uz:"rassom"},{en:"aunt",tr:"/ɑːnt/",uz:"xola, amma"},
{en:"boss",tr:"/bɒs/",uz:"boshliq, xo'jayin"},{en:"British",tr:"/ˈbrɪtɪʃ/",uz:"britaniyalik"},
{en:"brother",tr:"/ˈbrʌðə(r)/",uz:"aka, uka"},{en:"brother-in-law",tr:"/ˈbrʌðər ɪn lɔː/",uz:"qayn-og'a, pochcha"},
{en:"business management",tr:"/ˈbɪznəs ˈmænɪdʒmənt/",uz:"biznes boshqaruvi"},{en:"car mechanic",tr:"/kɑː mɪˈkænɪk/",uz:"avto-mexanik"},
{en:"child",tr:"/tʃaɪld/",uz:"bola"},{en:"children",tr:"/ˈtʃɪldrən/",uz:"bolalar"},
{en:"Chinese",tr:"/ˌtʃaɪˈniːz/",uz:"xitoylik"},{en:"communicate",tr:"/kəˈmjuːnɪkeɪt/",uz:"muloqot qilmoq"},
{en:"country",tr:"/ˈkʌntri/",uz:"mamlakat"},{en:"cousin",tr:"/ˈkʌzn/",uz:"amakivachcha, tog'avachcha"},
{en:"daughter",tr:"/ˈdɔːtə(r)/",uz:"qiz farzand"},{en:"designer",tr:"/dɪˈzaɪnə(r)/",uz:"dizayner"},
{en:"Emirati",tr:"/emɪˈrɑːti/",uz:"BAA fuqarosi"},{en:"family name",tr:"/ˈfæməlɪneɪm/",uz:"familiyasi, sharifi"},
{en:"father",tr:"/ˈfɑːðə(r)/",uz:"ota, dada"},{en:"fluent",tr:"/ˈfluːənt/",uz:"ravon"},
{en:"French",tr:"/frentʃ/",uz:"fransuz"},{en:"genetic",tr:"/dʒəˈnetɪk/",uz:"irsiy"},
{en:"granddaughter",tr:"/ˈɡrændɔːtə(r)/",uz:"nevara qiz"},{en:"grandfather",tr:"/ˈɡrænfɑːðə(r)/",uz:"bobo"},
{en:"grandmother",tr:"/ˈɡrænmʌðə(r)/",uz:"buvi, momo"},{en:"grandson",tr:"/ˈɡrænsʌn/",uz:"o'g'il nevara"},
{en:"Greek",tr:"/ɡriːk/",uz:"grek"},{en:"Hungarian",tr:"/hʌŋˈɡeərɪən/",uz:"vengriyalik"},
{en:"husband",tr:"/ˈhʌzbənd/",uz:"er"},{en:"introduce",tr:"/ˌɪntrəˈdjuːs/",uz:"tanishtirmoq"},
{en:"Italian",tr:"/ɪˈtælɪən/",uz:"italiyalik"},{en:"Japanese",tr:"/ˌdʒæpəˈniːz/",uz:"yaponiyalik"},
{en:"last name",tr:"/lɑːst nem/",uz:"familiya, sharif"},{en:"Lebanese",tr:"/ˌlebəˈniːz/",uz:"livanlik"},
{en:"married",tr:"/ˈmærid/",uz:"turmush qurgan"},{en:"Mexican",tr:"/ˈmeksɪkən/",uz:"meksikalik"},
{en:"mother",tr:"/ˈmʌðə(r)/",uz:"ona"},{en:"nationality",tr:"/ˌnæʃəˈnæləti/",uz:"millat"},
{en:"neighbour",tr:"/ˈneɪbə(r)/",uz:"qo'shni"},{en:"nephew",tr:"/ˈnefjuː/",uz:"jiyan (o'g'il bola)"},
{en:"niece",tr:"/niːs/",uz:"jiyan (qiz bola)"},{en:"Nigerian",tr:"/naɪˈdʒɪərɪən/",uz:"nigeriyalik"},
{en:"Pakistani",tr:"/ˌpækɪˈstɑːni/",uz:"pokistonlik"},{en:"Polish",tr:"/ˈpəʊlɪʃ/",uz:"polshalik"},
{en:"Portuguese",tr:"/ˌpɔːtʃuˈɡiːz/",uz:"portugaliyalik"},{en:"restaurant",tr:"/ˈrestrɒnt/",uz:"restoran"},
{en:"Russian",tr:"/ˈrʌʃn/",uz:"rus"},{en:"saxophone",tr:"/ˈsæksəfəʊn/",uz:"saksofon"},
{en:"single",tr:"/ˈsɪŋɡl/",uz:"turmush qurmagan, bo'ydoq"},{en:"sister",tr:"/ˈsɪstə(r)/",uz:"opa, singil"},
{en:"son",tr:"/sʌn/",uz:"o'g'il"},{en:"Spanish",tr:"/ˈspænɪʃ/",uz:"ispaniyalik"},
{en:"stepfather",tr:"/ˈstepfɑːðə(r)/",uz:"o'gay ota"},{en:"supermarket",tr:"/ˈsuːpəmɑːkt/",uz:"supermarket"},
{en:"Turkish",tr:"/ˈtɜːkɪʃ/",uz:"turk, turkiyalik"},{en:"twin",tr:"/twɪn/",uz:"egizak"},
{en:"typical",tr:"/ˈtɪpɪkl/",uz:"odatiy"},{en:"uncle",tr:"/ˈʌŋkl/",uz:"amaki, tog'a"},
{en:"unemployed",tr:"/ˌʌnɪmˈplɔɪd/",uz:"ishsiz"},{en:"Urdu",tr:"/ˈɜːduː/",uz:"Urdu"},
{en:"Vietnamese",tr:"/ˌvjetnəˈmiːz/",uz:"vyetnamlik"},{en:"wife",tr:"",uz:"xotin"}
]},
{id:'u2',name:'Elementary Unit 2',words:[
{en:"agree (with)",tr:"/əˈɡriː/",uz:"rozi bo'lmoq, kelishmoq"},{en:"alone",tr:"/əˈləʊn/",uz:"yolg'iz"},
{en:"ask (for)",tr:"/ɑːsk/",uz:"so'ramoq"},{en:"astronaut",tr:"/ˈæstrənɔːt/",uz:"astronavt, samogir"},
{en:"beach",tr:"/biːtʃ/",uz:"sohil"},{en:"body clock",tr:"/ˈbɒdɪklɒk/",uz:"biologik soat"},
{en:"break",tr:"/breɪk/",uz:"tanaffus"},{en:"breakfast",tr:"/ˈbrekfəst/",uz:"nonushta"},
{en:"canteen",tr:"/kænˈtiːn/",uz:"oshxona"},{en:"cereal",tr:"/ˈsɪərɪəl/",uz:"yorma"},
{en:"class",tr:"/klɑːs/",uz:"dars"},{en:"dangerous",tr:"/ˈdeɪndʒərəs/",uz:"xavfli"},
{en:"dirty",tr:"/ˈdɜːti/",uz:"kir, iflos"},{en:"discount",tr:"/ˈdɪskaʊnt/",uz:"chegirma"},
{en:"expert",tr:"/ˈekspɜːt/",uz:"mutaxassis"},{en:"eyesight",tr:"/ˈaɪsaɪt/",uz:"ko'rish qobiliyati, nigoh"},
{en:"feel well",tr:"/fiːlˈwel/",uz:"o'zini yaxshi his qilmoq"},{en:"free",tr:"/friː/",uz:"tekin"},
{en:"free time",tr:"/ˈfriːtaɪm/",uz:"bo'sh vaqt"},{en:"fresh air",tr:"/freʃˈeə(r)/",uz:"toza havo"},
{en:"get up",tr:"/ɡetˈʌp/",uz:"o'rnidan turmoq"},{en:"go",tr:"/ɡəʊ/",uz:"bormoq"},
{en:"go clubbing",tr:"/ɡəʊˈklʌbɪŋ/",uz:"klubga bormoq"},{en:"half past",tr:"/hɑːfˈpɑːst/",uz:"yarim soat o'tdi"},
{en:"have dinner",tr:"/hævˈdɪnə(r)/",uz:"kechki ovqatni yemoq"},{en:"have lunch",tr:"/hævˈlʌntʃ/",uz:"tushlik qilmoq"},
{en:"hungry",tr:"/ˈhʌŋɡri/",uz:"och (qorin)"},{en:"idea",tr:"/aɪˈdɪə/",uz:"g'oya"},
{en:"journey",tr:"/ˈdʒɜːni/",uz:"sayohat"},{en:"lab",tr:"/læb/",uz:"laboratoriya"},
{en:"lazy",tr:"/ˈleɪzi/",uz:"dangasa"},{en:"meal",tr:"/miːl/",uz:"taom"},
{en:"midnight",tr:"/ˈmɪdnaɪt/",uz:"yarim tun"},{en:"nap",tr:"/næp/",uz:"qisqa uyqu"},
{en:"never",tr:"/ˈnevə(r)/",uz:"hech qachon"},{en:"normally",tr:"/ˈnɔːməli/",uz:"odatda"},
{en:"often",tr:"/ˈɒfn/",uz:"tez-tez"},{en:"quarter",tr:"/ˈkwɔːtə(r)/",uz:"chorak"},
{en:"routine",tr:"/ruːˈtiːn/",uz:"kundalik tartib"},{en:"sometimes",tr:"/ˈsʌmtaɪmz/",uz:"ba'zida"},
{en:"space",tr:"/speɪs/",uz:"kosmos, fazo"},{en:"star",tr:"/stɑː(r)/",uz:"yulduz"},
{en:"stop",tr:"/stɒp/",uz:"to'xtamoq"},{en:"student card",tr:"/ˈstjuːdntˌkɑːd/",uz:"talabalar guvohnomasi"},
{en:"think (about)",tr:"/θɪŋk/",uz:"(haqida) o'ylamoq"},{en:"tired",tr:"/ˈtaɪəd/",uz:"charchagan"},
{en:"title",tr:"/ˈtaɪtl/",uz:"unvon"},{en:"toast",tr:"/təʊst/",uz:"qizdirilgan non"},
{en:"trainee",tr:"/ˌtreɪˈniː/",uz:"ish o'rganuvchi"},{en:"volcano",tr:"/vɒlˈkeɪnəʊ/",uz:"vulqon"},
{en:"wait",tr:"/weɪt/",uz:"kutmoq"},{en:"wake up",tr:"/weɪkˈʌp/",uz:"uyg'onmoq"},
{en:"wall",tr:"/wɔːl/",uz:"devor"},{en:"watch a film",tr:"/wɒtʃəˈfɪlm/",uz:"kino tomosha qilmoq"},
{en:"watch TV",tr:"/wɒtʃˌtiːˈviː/",uz:"televizor ko'rmoq"},{en:"work",tr:"/wɜː(r)k/",uz:"ishlamoq"},
{en:"zoology",tr:"/zuˈɒlədʒi/",uz:"zoologiya"}
]},
{id:'u3',name:'Elementary Unit 3',words:[
{en:"address",tr:"/əˈdres/",uz:"manzil"},{en:"administrator",tr:"/ədˈmɪnɪstreɪtə(r)/",uz:"ma'mur"},
{en:"again",tr:"/əˈɡen/",uz:"yana"},{en:"airline",tr:"/ˈeəlaɪn/",uz:"aviakompaniya"},
{en:"answer",tr:"/ˈɑːnsə(r)/",uz:"javob"},{en:"author",tr:"/ˈɔːθə(r)/",uz:"muallif"},
{en:"baker",tr:"/ˈbeɪkə(r)/",uz:"novvoy"},{en:"beginner",tr:"/bɪˈɡɪnə(r)/",uz:"boshlang'ich, bosqich o'quvchisi"},
{en:"builder",tr:"/ˈbɪldə(r)/",uz:"quruvchi"},{en:"bus driver",tr:"/ˈbʌs ˌdraɪvə(r)/",uz:"avtobus haydovchisi"},
{en:"businessman",tr:"/ˈbɪznəsmæn/",uz:"tadbirkor"},{en:"businesswoman",tr:"/ˈbɪznəswʊmən/",uz:"tadbirkor ayol"},
{en:"calm",tr:"/kɑːm/",uz:"tinch, bosiq"},{en:"chef",tr:"/ʃef/",uz:"bosh oshpaz"},
{en:"cleaner",tr:"/ˈkliːnə(r)/",uz:"farrosh"},{en:"clever",tr:"/ˈklevə(r)/",uz:"aqlli"},
{en:"colleague",tr:"/ˈkɒliːɡ/",uz:"hamkasb"},{en:"company",tr:"/ˈkæmpəni/",uz:"kompaniya"},
{en:"dancer",tr:"/ˈdɑːnsə(r)/",uz:"raqqos(a)"},{en:"dentist",tr:"/ˈdentɪst/",uz:"tish shifokori"},
{en:"driver",tr:"/ˈdraɪvə(r)/",uz:"haydovchi"},{en:"earn",tr:"/ɜːn/",uz:"pul ishlab topmoq"},
{en:"factory",tr:"/ˈfæktri/",uz:"zavod"},{en:"farmer",tr:"/ˈfɑːmə(r)/",uz:"dehqon"},
{en:"fix",tr:"/fɪks/",uz:"tuzatmoq"},{en:"forest",tr:"/ˈfɒrɪst/",uz:"o'rmon"},
{en:"forget",tr:"/fəˈɡet/",uz:"unutmoq"},{en:"hairdresser",tr:"/ˈheəˌdresə(r)/",uz:"sartarosh"},
{en:"important",tr:"/ɪmˈpɔːtnt/",uz:"muhim"},{en:"inside",tr:"/ˌɪnˈsaɪd/",uz:"ichkarida"},
{en:"internet",tr:"/ˈɪntənet/",uz:"internet"},{en:"journalist",tr:"/ˈdʒɜːnəlɪst/",uz:"jurnalist"},
{en:"later",tr:"/ˈleɪtə(r)/",uz:"keyinroq"},{en:"lonely",tr:"/ˈləʊnli/",uz:"yolg'iz"},
{en:"lookout",tr:"/ˈlʊkaʊt/",uz:"kuzatuvchi"},{en:"lucky",tr:"/ˈlʌki/",uz:"omadli"},
{en:"magazine",tr:"/ˌmæɡəˈziːn/",uz:"jurnal"},{en:"manager",tr:"/ˈmænɪdʒə(r)/",uz:"ish boshqaruvchi"},
{en:"money",tr:"/ˈmʌni/",uz:"pul"},{en:"Mp3 player",tr:"/ˌem piː ˈθriː/",uz:"mp3 pleyer"},
{en:"musician",tr:"/mjuˈzɪʃn/",uz:"sozanda"},{en:"nurse",tr:"/nɜːs/",uz:"hamshira"},
{en:"office worker",tr:"/ˈɒfɪs ˌwɜːkə(r)/",uz:"idora xodimi"},{en:"painter",tr:"/ˈpeɪntə(r)/",uz:"musavvir"},
{en:"part-time",tr:"/ˌpɑːtˈtaɪm/",uz:"yarim stavkada"},{en:"photographer",tr:"/fəˈtɒɡrəfə(r)/",uz:"fotosuratchi"},
{en:"piano",tr:"/pɪˈænəʊ/",uz:"pianino"},{en:"pilot",tr:"/ˈpaɪlət/",uz:"uchuvchi"},
{en:"place of work",tr:"/ˌpleɪsəvˈwɜːk/",uz:"ish joyi"},{en:"police officer",tr:"/pəˈliːs ˌɒfɪsə(r)/",uz:"militsiya zobiti"},
{en:"retired",tr:"/rɪˈtaɪəd/",uz:"nafaqaga chiqqan"},{en:"salary",tr:"/ˈsæləri/",uz:"ish haqi, maosh"},
{en:"silent",tr:"/ˈsaɪlənt/",uz:"ovozsiz"},{en:"singer",tr:"/ˈsɪŋə(r)/",uz:"qo'shiqchi"},
{en:"student",tr:"/ˈstjuːdnt/",uz:"talaba, o'quvchi"},{en:"teacher",tr:"/ˈtiːtʃə(r)/",uz:"o'qituvchi"},
{en:"ticket",tr:"/ˈtɪkɪt/",uz:"chipta"},{en:"tower",tr:"/ˈtaʊə(r)/",uz:"minora"},
{en:"uniform",tr:"/ˈjuːnɪfɔːm/",uz:"maxsus kiyim"},{en:"unusual",tr:"/ˌʌnˈjuːʒuəl/",uz:"noodatiy"},
{en:"well-paid",tr:"/ˌwelˈpeɪd/",uz:"yaxshi maoshli"},{en:"winner",tr:"/ˈwɪnə(r)/",uz:"g'olib"},
{en:"work freelance",tr:"/ˌwɜːkˈfriːlɑːns/",uz:"mustaqil ishlamoq"},{en:"work long hours",tr:"/ˌwɜːkˌlɒŋˈaʊəz/",uz:"uzoq vaqt ishlamoq"},
{en:"writer",tr:"/ˈraɪtə(r)/",uz:"yozuvchi"}
]},
{id:'u4',name:'Elementary Unit 4',words:[
{en:"above",tr:"/əˈbʌv/",uz:"tepasida"},{en:"airport",tr:"/ˈeəpɔːt/",uz:"aeroport"},
{en:"armchair",tr:"/ˈɑːmtʃeə(r)/",uz:"kreslo"},{en:"bank",tr:"/bæŋk/",uz:"bank"},
{en:"bathroom",tr:"/ˈbɑːθruːm/",uz:"hammom"},{en:"bed",tr:"/bed/",uz:"krovat"},
{en:"bedroom",tr:"/ˈbedrʊm/",uz:"yotoqxona"},{en:"behind",tr:"/bɪˈhaɪnd/",uz:"orqasida"},
{en:"between",tr:"/bɪˈtwiːn/",uz:"orasida"},{en:"big",tr:"/bɪɡ/",uz:"katta"},
{en:"booking form",tr:"/ˈbʊkɪŋfɔːm/",uz:"buyurtma berish formasi"},{en:"bookshop",tr:"/ˈbʊkʃɒp/",uz:"kitob do'koni"},
{en:"building",tr:"/ˈbɪldɪŋ/",uz:"bino"},{en:"campsite",tr:"/ˈkæmpsaɪt/",uz:"oromgoh"},
{en:"capital",tr:"/ˈkæpɪtl/",uz:"poytaxt"},{en:"carpet",tr:"/ˈkɑːpɪt/",uz:"gilam"},
{en:"cheap",tr:"/tʃiːp/",uz:"arzon"},{en:"chemist's",tr:"/ˈkemɪsts/",uz:"dorixona"},
{en:"cinema",tr:"/ˈsɪnəmə/",uz:"kinoteatr"},{en:"clean",tr:"/kliːn/",uz:"toza"},
{en:"cooker",tr:"/ˈkʊkə(r)/",uz:"gaz plitasi"},{en:"dining room",tr:"/ˈdaɪnɪŋruːm/",uz:"tamaddixona"},
{en:"dishwasher",tr:"/ˈdɪʃwɒʃə(r)/",uz:"idish yuvish mashinasi"},{en:"easy",tr:"/ˈiːzi/",uz:"oson"},
{en:"expensive",tr:"/ɪkˈspensɪv/",uz:"qimmat"},{en:"fantastic",tr:"/fænˈtæstɪk/",uz:"ajoyib"},
{en:"flat",tr:"/flæt/",uz:"xonadon"},{en:"fridge",tr:"/frɪdʒ/",uz:"sovutgich"},
{en:"furniture",tr:"/ˈfɜːnɪtʃə(r)/",uz:"mebel"},{en:"garage",tr:"/ˈɡærɑːʒ, ˈɡærɪdʒ/",uz:"garaj"},
{en:"hairdresser's",tr:"/ˈheədresəz/",uz:"sartaroshxona"},{en:"hospital",tr:"/ˈhɒspɪtl/",uz:"kasalxona"},
{en:"housemate",tr:"/ˈhaʊsmeɪt/",uz:"xonadosh, hamxona"},{en:"in front of",tr:"/ɪnˈfrɒntəv/",uz:"old tomonida"},
{en:"instructions",tr:"/ɪnˈstrʌkʃnz/",uz:"ko'rsatmalar"},{en:"kitchen",tr:"/ˈkɪtʃɪn/",uz:"oshxona"},
{en:"launderette",tr:"/ˌlɔːnˈdret/",uz:"kir yuvish shahobchasi"},{en:"lazy",tr:"/ˈleɪzi/",uz:"dangasa"},
{en:"library",tr:"/ˈlaɪbrəri/",uz:"kutubxona"},{en:"light",tr:"/laɪt/",uz:"yorug'"},
{en:"living room",tr:"/ˈlɪvɪŋruːm/",uz:"mehmonxona"},{en:"market",tr:"/ˈmɑːkɪt/",uz:"bozor"},
{en:"messy",tr:"/ˈmesi/",uz:"tartibsiz"},{en:"mine",tr:"/maɪn/",uz:"kon"},
{en:"museum",tr:"/mjuˈziːəm/",uz:"muzey"},{en:"next to",tr:"/ˈneksttuː, tə/",uz:"yon tomonida"},
{en:"old",tr:"/əʊld/",uz:"eski"},{en:"old-fashioned",tr:"/ˌəʊldˈfæʃnd/",uz:"eskicha"},
{en:"on",tr:"/ɒn/",uz:"(usti)da"},{en:"opal",tr:"/ˈəʊpl/",uz:"opal (qimmatbaho tosh)"},
{en:"opposite",tr:"/ˈɒpəzɪt/",uz:"qarshisida, ro'parasida"},{en:"organized",tr:"/ˈɔːɡənaɪzd/",uz:"tartibli"},
{en:"palace",tr:"/ˈpæləs/",uz:"saroy"},{en:"passport",tr:"/ˈpɑːspɔːt/",uz:"pasport"},
{en:"post office",tr:"/ˈpəʊstˌɒfɪs/",uz:"pochta idorasi"},{en:"railway station",tr:"/ˈreɪlweɪ ˌsteɪʃn/",uz:"vokzal"},
{en:"scarf",tr:"/skɑːf/",uz:"sharf"},{en:"shelf",tr:"/ʃelf/",uz:"javon"},
{en:"sink",tr:"/sɪŋk/",uz:"rakovina"},{en:"studio flat",tr:"/ˈstjuːdiəʊflæt/",uz:"bir xonadan tashkil topgan xonadon"},
{en:"swimming pool",tr:"/ˈswɪmɪŋpuːl/",uz:"suzish havzasi"},{en:"table",tr:"/ˈteɪbl/",uz:"stol"},
{en:"temple",tr:"/ˈtempl/",uz:"ibodatxona"},{en:"terrible",tr:"/ˈterəbl/",uz:"juda yomon, ayanchli"},
{en:"theatre",tr:"/ˈθɪətə(r)/",uz:"teatr"},{en:"tidy",tr:"/ˈtaɪdi/",uz:"orasta"},
{en:"toilet",tr:"/ˈtɔɪlət/",uz:"xojatxona"},{en:"tour",tr:"/tɔː(r)/",uz:"sayohat, tur, ekskursiya"},
{en:"tourist",tr:"/ˈtʊərɪst/",uz:"sayyoh"},{en:"tourist information centre",tr:"/ˈtʊərɪst ˌɪnfəˈmeɪʃn ˌsentə(r)/",uz:"sayyohlik axborot markazi"},
{en:"town",tr:"/taʊn/",uz:"shahar(cha)"},{en:"travel",tr:"/ˈtrævl/",uz:"sayohat qilmoq"},
{en:"ugly",tr:"/ˈʌɡli/",uz:"xunuk"},{en:"under",tr:"/ˈʌndə(r)/",uz:"ostida"},
{en:"underground",tr:"/ˈʌndəˌɡraʊnd/",uz:"yerosti"},{en:"visit",tr:"/ˈvɪzɪt/",uz:"tashrif buyurmoq"},
{en:"washing machine",tr:"/ˈwɒʃɪŋməˌʃiːn/",uz:"kir yuvish mashinasi"},{en:"window",tr:"/ˈwɪndəʊ/",uz:"oyna, deraza"}
]},
{id:'u5',name:'Elementary Unit 5',words:[
{en:"baker's",tr:"/ˈbeɪkəz/",uz:"nonvoyxona"},{en:"boring",tr:"/ˈbɔːrɪŋ/",uz:"zerikarli"},
{en:"butcher's",tr:"/ˈbʊtʃəz/",uz:"go'sht do'koni"},{en:"button",tr:"/ˈbʌtn/",uz:"tugma"},
{en:"careful",tr:"/ˈkeəfl/",uz:"ehtiyotkor"},{en:"carefully",tr:"/ˈkeəfəli/",uz:"ehtiyotkorlik bilan"},
{en:"cash",tr:"/kæʃ/",uz:"naqd pul"},{en:"changing room",tr:"/ˈtʃeɪndʒɪŋruːm/",uz:"kiyim almashtirish xonasi"},
{en:"clear",tr:"/klɪə(r)/",uz:"tiniq"},{en:"clearly",tr:"/ˈklɪəli/",uz:"aniq (holda)"},
{en:"coat",tr:"/kəʊt/",uz:"palto"},{en:"correct",tr:"/kəˈrekt/",uz:"to'g'ri"},
{en:"correctly",tr:"/kəˈrektli/",uz:"to'g'ri (holda)"},{en:"dangerously",tr:"/ˈdeɪndʒərəsli/",uz:"xavfli tarzda"},
{en:"designer shoes",tr:"/dɪˌzaɪnəˈʃuːz/",uz:"maxsus tikilgan oyoq kiyim(lar)"},{en:"disappointed",tr:"/ˌdɪsəˈpɔɪntɪd/",uz:"xafa, hafsalasi pir bo'lgan"},
{en:"dress",tr:"/dres/",uz:"ko'ylak (ayollar)"},{en:"gloves",tr:"/ɡlʌvz/",uz:"qo'lqop"},
{en:"good",tr:"/ɡʊd/",uz:"yaxshi"},{en:"great",tr:"/ɡreɪt/",uz:"katta, buyuk"},
{en:"hat",tr:"/hæt/",uz:"shlyapa"},{en:"heavy",tr:"/ˈhevi/",uz:"og'ir"},
{en:"hoodie",tr:"/ˈhʊdi/",uz:"qaytarma qalpoqli kiyim, tolstovka"},{en:"information",tr:"/ˌɪnfəˈmeɪʃn/",uz:"ma'lumot"},
{en:"jacket",tr:"/ˈdʒækɪt/",uz:"kurtka; pidjak"},{en:"jeans",tr:"/dʒiːnz/",uz:"jinsi shim"},
{en:"jewellery",tr:"/ˈdʒuːəlri/",uz:"zargarlik buyumlari"},{en:"meat",tr:"/miːt/",uz:"go'sht"},
{en:"newsagent's",tr:"/ˈnjuːzeɪdʒənts/",uz:"matbuot do'koni"},{en:"online",tr:"/ˈɒnlaɪn/",uz:"internetda, onlayn"},
{en:"poor",tr:"/pɔː(r)/",uz:"qoniqarsiz, nochor, zaif"},{en:"postcard",tr:"/ˈpəʊstkɑːd/",uz:"tabriknoma"},
{en:"quiet",tr:"/ˈkwaɪət/",uz:"jim, sokin"},{en:"quietly",tr:"/ˈkwaɪətli/",uz:"past ovozda"},
{en:"rain water",tr:"/ˈreɪnwɔːtə(r)/",uz:"yomg'ir suvi"},{en:"reading glasses",tr:"/ˈriːdɪŋɡlɑːsɪz/",uz:"o'qish ko'zoynagi"},
{en:"receipt",tr:"/rɪˈsiːt/",uz:"kvitantsiya"},{en:"recommend",tr:"/ˌrekəˈmend/",uz:"tavsiya qilmoq"},
{en:"relax",tr:"/rɪˈlæks/",uz:"dam olmoq"},{en:"return",tr:"/rɪˈtɜːn/",uz:"qaytarib bermoq"},
{en:"sales",tr:"/seɪlz/",uz:"arzonlashtirilgan mollar sotuvi"},{en:"serious",tr:"/ˈsɪəriəs/",uz:"jiddiy"},
{en:"shopping centre",tr:"/ˈʃɒpɪŋˌsentə(r)/",uz:"savdo markazi"},{en:"shorts",tr:"/ʃɔːts/",uz:"shortik"},
{en:"simple",tr:"/ˈsɪmpl/",uz:"oddiy"},{en:"skirt",tr:"/skɜːt/",uz:"yubka"},
{en:"slow",tr:"/sləʊ/",uz:"sekin"},{en:"slowly",tr:"/ˈsləʊli/",uz:"sekinlik bilan"},
{en:"socks",tr:"/sɒks/",uz:"paypoq"},{en:"spend",tr:"/spend/",uz:"sarflamoq"},
{en:"suit",tr:"/suːt/",uz:"kostyum-shim"},{en:"strong",tr:"/strɒŋ/",uz:"kuchli"},
{en:"tie",tr:"/taɪ/",uz:"bo'yinbog'"},{en:"trainers",tr:"/ˈtreɪnəz/",uz:"krossovki"},
{en:"trousers",tr:"/ˈtraʊzəz/",uz:"shim"},{en:"T-shirt",tr:"/ˈtiːʃɜːt/",uz:"futbolka"},
{en:"umbrella",tr:"/ʌmˈbrelə/",uz:"soyabon"},{en:"value",tr:"/ˈvæljuː/",uz:"qiymat, qadr"},
{en:"vending machine",tr:"/ˈvendɪŋməʃiːn/",uz:"savdo mashinasi"},{en:"virtual",tr:"/ˈvɜːtʃuəl/",uz:"kompyuter yoki internetda yaratilgan"},
{en:"wedding",tr:"/ˈwedɪŋ/",uz:"to'y"},{en:"well",tr:"/wel/",uz:"yaxshi (tarzda)"},
{en:"worth",tr:"/wɜːθ/",uz:"arzigulik"}
]},
{id:'u6',name:'Elementary Unit 6',words:[
{en:"a bit",tr:"/əˈbɪt/",uz:"ozgina, biroz"},{en:"believe",tr:"/bɪˈliːv/",uz:"ishonmoq"},
{en:"bobsleigh",tr:"/ˈbɒbsleɪ/",uz:"bobsley-sport turi"},{en:"call",tr:"/kɔːl/",uz:"qo'ng'iroq qilmoq, chaqirmoq"},
{en:"change",tr:"/tʃeɪndʒ/",uz:"o'zgartirmoq, o'zgartirmoq"},{en:"classroom",tr:"/ˈklɑːsruːm/",uz:"sinf xonasi, o'quv xonasi"},
{en:"collect",tr:"/kəˈlekt/",uz:"to'plamoq"},{en:"copy",tr:"/ˈkɒpi/",uz:"nusxa ko'chirmoq"},
{en:"decide",tr:"/dɪˈsaɪd/",uz:"qaror qilmoq"},{en:"fashion designer",tr:"/ˈfæʃndɪˌzaɪnə(r)/",uz:"modelyer, moda dizayneri"},
{en:"finish",tr:"/ˈfɪnɪʃ/",uz:"tugatmoq"},{en:"founder",tr:"/ˈfaʊndə(r)/",uz:"asoschi"},
{en:"ice skater",tr:"/ˈaɪs ˌskeɪtə(r)/",uz:"konkida uchuvchi"},{en:"interesting",tr:"/ˈɪntrəstɪŋ/",uz:"qiziqarli"},
{en:"label",tr:"/ˈleɪbl/",uz:"yorliq, belgi"},{en:"like",tr:"/laɪk/",uz:"yoqtirmoq"},
{en:"live",tr:"/lɪv/",uz:"yashamoq, kun kechirmoq"},{en:"look at",tr:"/lʊk/",uz:"qaramoq"},
{en:"love",tr:"/lʌv/",uz:"sevmoq"},{en:"modern art",tr:"/ˌmɒdnˈɑːt/",uz:"zamonaviy san'at"},
{en:"move",tr:"/muːv/",uz:"ko'chmoq"},{en:"naughty",tr:"/ˈnɔːti/",uz:"itoatsiz, betartib"},
{en:"notice",tr:"/ˈnəʊtɪs/",uz:"payqamoq, sezib qolmoq"},{en:"open",tr:"/ˈəʊpən/",uz:"ochmoq"},
{en:"play",tr:"/pleɪ/",uz:"o'ynamoq"},{en:"popular",tr:"/ˈpɒpjələ(r)/",uz:"taniqli, mashhur"},
{en:"post",tr:"/pəʊst/",uz:"pochta orqali jo'natmoq"},{en:"prepare",tr:"/prɪˈpeə(r)/",uz:"tayyorlamoq"},
{en:"product",tr:"/ˈprɒdʌkt/",uz:"mahsulot"},{en:"quite",tr:"/kwaɪt/",uz:"ancha, yetarlicha"},
{en:"really",tr:"/ˈriːəli/",uz:"haqiqatdan ham, juda"},{en:"receive",tr:"/rɪˈsiːv/",uz:"qabul qilmoq, olmoq"},
{en:"return",tr:"/rɪˈtɜːn/",uz:"qaytmoq, qaytarmoq"},{en:"sculpture",tr:"/ˈskʌlptʃə(r)/",uz:"haykal"},
{en:"shout",tr:"/ʃaʊt/",uz:"baqirmoq"},{en:"start",tr:"/stɑːt/",uz:"boshlamoq"},
{en:"study",tr:"/ˈstʌdi/",uz:"o'qimoq, tahsil olmoq"},{en:"successful",tr:"/səkˈsesfl/",uz:"muvaffaqiyatli"},
{en:"talk",tr:"/tɔːk/",uz:"gapirmoq, suhbat qurmoq"},{en:"thank",tr:"/θæŋk/",uz:"minnatdorlik bildirmoq"},
{en:"use",tr:"/juːz/",uz:"foydalanmoq, ishlatmoq"},{en:"very",tr:"/ˈveri/",uz:"juda"},
{en:"want",tr:"/wɒnt/",uz:"xohlamoq"},{en:"watch",tr:"/wɒtʃ/",uz:"tomosha qilmoq"}
]},
{id:'u7',name:'Elementary Unit 7',words:[
{en:"app",tr:"/næp/",uz:"ilova"},{en:"athletics",tr:"/æθˈletɪks/",uz:"yengil atletika"},
{en:"ban",tr:"/bæn/",uz:"man etmoq"},{en:"basketball",tr:"/ˈbɑːskɪtbɔːl/",uz:"basketbol"},
{en:"borrow",tr:"/ˈbɒrəʊ/",uz:"qarzga olmoq"},{en:"bring",tr:"/brɪŋ/",uz:"keltirmoq, olib kelmoq"},
{en:"bucket",tr:"/ˈbʌkɪt/",uz:"chelak"},{en:"come",tr:"/kʌm/",uz:"kelmoq"},
{en:"cycle",tr:"/ˈsaɪkl/",uz:"velosiped haydamoq"},{en:"do",tr:"/duː/",uz:"bajarmoq, qilmoq"},
{en:"drink",tr:"/drɪŋk/",uz:"ichmoq"},{en:"eat",tr:"/iːt/",uz:"yemoq, tanovvul qilmoq"},
{en:"fit",tr:"/fɪt/",uz:"sog'lom, tetik"},{en:"football",tr:"/ˈfʊtbɔːl/",uz:"futbol"},
{en:"gadget",tr:"/ˈɡædʒɪt/",uz:"qurilma"},{en:"go fishing",tr:"/ɡəʊˈfɪʃɪŋ/",uz:"baliq oviga bormoq"},
{en:"gym",tr:"/dʒɪm/",uz:"gimnastika zali"},{en:"habit",tr:"/ˈhæbɪt/",uz:"odat"},
{en:"healthy",tr:"/ˈhelθi/",uz:"sog'lom"},{en:"hero",tr:"/ˈhɪərəʊ/",uz:"qahramon"},
{en:"jog",tr:"/dʒɒɡ/",uz:"yengil yugurish"},{en:"judo",tr:"/ˈdʒuːdəʊ/",uz:"dzyudo"},
{en:"learn",tr:"/lɜːn/",uz:"o'rganmoq"},{en:"lend",tr:"/lend/",uz:"qarzga bermoq"},
{en:"lift",tr:"/lɪft/",uz:"ko'tarmoq, podnimat'"},{en:"lightning",tr:"/ˈlaɪtnɪŋ/",uz:"chaqmoq"},
{en:"local",tr:"/ˈləʊkl/",uz:"mahalliy"},{en:"lose",tr:"/luːz/",uz:"yo'qotmoq"},
{en:"marathon",tr:"/ˈmærəθən/",uz:"marafon"},{en:"mayor",tr:"/meə(r)/",uz:"shahar hokimi"},
{en:"opinion",tr:"/əˈpɪnjən/",uz:"fikr"},{en:"paperclip",tr:"/ˈpeɪpəklɪp/",uz:"qog'oz qisqichi"},
{en:"physical",tr:"/ˈfɪzɪkl/",uz:"jismoniy"},{en:"progress",tr:"/ˈprəʊɡres/",uz:"rivojlanish"},
{en:"reduce",tr:"/rɪˈdjuːs/",uz:"kamaytirmoq, qisqartirmoq"},{en:"research",tr:"/rɪˈsɜːtʃ/",uz:"izlanish"},
{en:"ride",tr:"/raɪd/",uz:"minmoq, velosiped haydamoq"},{en:"routine",tr:"/ruːˈtiːn/",uz:"kundalik ish"},
{en:"run",tr:"/rʌn/",uz:"yugurmoq"},{en:"sleep",tr:"/sliːp/",uz:"uxlamoq"},
{en:"studio",tr:"/ˈstjuːdiəʊ/",uz:"studiya"},{en:"subtitle",tr:"/ˈsʌbtaɪtl/",uz:"subtitr"},
{en:"swim",tr:"/swɪm/",uz:"suzmoq"},{en:"take",tr:"/teɪk/",uz:"olmoq"},
{en:"tennis",tr:"/ˈtenɪs/",uz:"tennis"},{en:"thunderstorm",tr:"/ˈθʌndəstɔːm/",uz:"momoqaldiroq"},
{en:"violent",tr:"/ˈvaɪələnt/",uz:"shavqatsiz"},{en:"walk",tr:"/wɔːk/",uz:"piyoda yurmoq"},
{en:"win",tr:"/wɪn/",uz:"g'alaba qozonmoq"},{en:"yoga",tr:"/ˈjəʊɡə/",uz:"yoga"}
]},
{id:'u8',name:'Elementary Unit 8',words:[
{en:"air-conditioned",tr:"/ˌeəkənˈdɪʃnd/",uz:"havo sovutgichli"},{en:"amazing",tr:"/əˈmeɪzɪŋ/",uz:"ajablanarli, g'aroyib"},
{en:"apartment",tr:"/əˈpɑːtmənt/",uz:"kvartira"},{en:"art gallery",tr:"/ˈɑːt ˌɡæləri/",uz:"san'at galereyasi"},
{en:"bike",tr:"/baɪk/",uz:"velosiped"},{en:"bus",tr:"/bʌs/",uz:"avtobus"},
{en:"car",tr:"/kɑː(r)/",uz:"yengil mashina"},{en:"city break",tr:"/ˈsɪti ˌbreɪk/",uz:"shahar ta'tili"},
{en:"colourful",tr:"/ˈkʌləfl/",uz:"rangli"},{en:"countryside",tr:"/ˈkʌntrɪsaɪd/",uz:"qishloq"},
{en:"culture",tr:"/ˈkʌltʃə(r)/",uz:"madaniyat"},{en:"dinner",tr:"/ˈdɪnə(r)/",uz:"tushlik"},
{en:"employee",tr:"/ˌɪmˈplɔɪiː/",uz:"ishchi"},{en:"environment",tr:"/ɪnˈvaɪrənmənt/",uz:"atrof-muhit"},
{en:"get",tr:"/ɡet/",uz:"olmoq, qabul qilmoq"},{en:"get around",tr:"/ˌɡetəˈraʊnd/",uz:"aylanmoq, xarakatlanmoq"},
{en:"group",tr:"/ɡruːp/",uz:"guruh"},{en:"guest house",tr:"/ˈɡesthaʊs/",uz:"mehmonxona (arzon turdagi)"},
{en:"guide",tr:"/ɡaɪd/",uz:"yo'l boshlovchi"},{en:"helmet",tr:"/ˈhelmɪt/",uz:"dubulg'a, kaska"},
{en:"hold",tr:"/həʊld/",uz:"ushlamoq, ushlab turmoq"},{en:"lie",tr:"/laɪ/",uz:"yotmoq"},
{en:"map",tr:"/mæp/",uz:"xarita"},{en:"miss",tr:"/mɪs/",uz:"o'tkazib yubormoq, ulgurmaslik"},
{en:"mountain",tr:"/ˈmaʊntən/",uz:"tog'"},{en:"passenger",tr:"/ˈpæsɪndʒə(r)/",uz:"yo'lovchi"},
{en:"platform",tr:"/ˈplætfɔːm/",uz:"platforma, minbar"},{en:"queue",tr:"/kjuː/",uz:"navbat"},
{en:"railway",tr:"/ˈreɪlweɪ/",uz:"temir yo'l"},{en:"rainforest",tr:"/ˈreɪnfɒrɪst/",uz:"tropik o'rmon"},
{en:"rent",tr:"/rent/",uz:"ijaraga olmoq"},{en:"return",tr:"/rɪˈtɜːn/",uz:"borib qaytish chiptasi"},
{en:"ruins",tr:"/ˈruːɪnz/",uz:"xarobalar"},{en:"seat belt",tr:"/ˈsiːtbelt/",uz:"xavfsizlik kamari"},
{en:"sightseeing",tr:"/ˈsaɪtsiːɪŋ/",uz:"diqqatga sazovor joylar"},{en:"single",tr:"/ˈsɪŋɡl/",uz:"bir tomonlama chipta"},
{en:"street life",tr:"/ˈstriːtlaɪf/",uz:"shahar hayoti"},{en:"sunrise",tr:"/ˈsʌnraɪz/",uz:"quyosh chiqishi"},
{en:"taxi",tr:"/ˈtæksi/",uz:"taksi"},{en:"text message",tr:"/ˈtekstˌmesɪdʒ/",uz:"matnli xabar"},
{en:"tip",tr:"/tɪp/",uz:"choychaqa, choy puli"},{en:"tradition",tr:"/trəˈdɪʃn/",uz:"urf-odat"},
{en:"train",tr:"/treɪn/",uz:"poyezd"},{en:"trek",tr:"/trek/",uz:"piyoda safarga chiqish"}
]},
{id:'u9',name:'Elementary Unit 9',words:[
{en:"bake",tr:"/beɪk/",uz:"pechda pishirmoq, yopmoq"},{en:"beef",tr:"/biːf/",uz:"mol go'shti"},
{en:"boil",tr:"/bɔɪl/",uz:"qaynatmoq"},{en:"bowl",tr:"/bəʊl/",uz:"tog'ora; kosa"},
{en:"bread",tr:"/bred/",uz:"non"},{en:"castle",tr:"/ˈkɑːsl/",uz:"qasr"},
{en:"chicken",tr:"/ˈtʃɪkɪn/",uz:"tovuq (tovuqli ovqat)"},{en:"chop",tr:"/tʃɒp/",uz:"to'gramoq, chopmoq"},
{en:"cube",tr:"/kjuːb/",uz:"go'sht bo'lagi"},{en:"delicious",tr:"/dɪˈlɪʃəs/",uz:"mazali"},
{en:"food processor",tr:"/ˈfuːd ˌprəʊsesə(r)/",uz:"oshxona kombayni"},{en:"fork",tr:"/fɔːk/",uz:"sanchqi"},
{en:"fruit",tr:"/fruːt/",uz:"meva"},{en:"fry",tr:"/fraɪ/",uz:"qovurmoq"},
{en:"frying pan",tr:"/ˈfraɪŋpæn/",uz:"tova"},{en:"honey",tr:"/ˈhʌni/",uz:"asal"},
{en:"ingredient",tr:"/ɪnˈɡriːdiənt/",uz:"mahsulot"},{en:"jam",tr:"/dʒæm/",uz:"murabbo"},
{en:"kettle",tr:"/ˈketl/",uz:"chovgun (uchun qaynatish)"},{en:"knife",tr:"/naɪf/",uz:"pichoq"},
{en:"lemon",tr:"/ˈlemən/",uz:"limon"},{en:"lemonade",tr:"/ˌleməˈneɪd/",uz:"limonad"},
{en:"main course",tr:"/ˈmeɪnkɔːs/",uz:"asosiy ovqat"},{en:"microwave",tr:"/ˈmaɪkrəweɪv/",uz:"mikro to'lqinli pech"},
{en:"mix",tr:"/mɪks/",uz:"aralashtirmoq"},{en:"mushroom",tr:"/ˈmʌʃrʊm/",uz:"qo'ziqorin"},
{en:"noodles",tr:"/ˈnuːdlz/",uz:"ugra"},{en:"olive",tr:"/ˈɒlɪv/",uz:"zaytun"},
{en:"oven",tr:"/ˈʌvn/",uz:"pech"},{en:"pasta",tr:"/ˈpæstə/",uz:"makaron"},
{en:"pear",tr:"/peə(r)/",uz:"nok"},{en:"plate",tr:"/pleɪt/",uz:"likopcha, tarelka"},
{en:"prepare",tr:"/prɪˈpeə(r)/",uz:"tayyorlamoq"},{en:"ready-made",tr:"/ˌrediˈmeɪd/",uz:"tayyor"},
{en:"rice",tr:"/raɪs/",uz:"guruch"},{en:"roast",tr:"/rəʊst/",uz:"olovda pishirmoq"},
{en:"rooftop",tr:"/ˈruːftɒp/",uz:"tom usti"},{en:"salad",tr:"/ˈsæləd/",uz:"salat"},
{en:"saucepan",tr:"/ˈsɔːspən/",uz:"kastryulya"},{en:"secret",tr:"/ˈsiːkrɪt/",uz:"sir"},
{en:"spoon",tr:"/spuːn/",uz:"qoshiq"},{en:"starter",tr:"/ˈstɑːtə(r)/",uz:"gazak; birinchi ovqat"},
{en:"sweet",tr:"/swiːt/",uz:"shirin"},{en:"survey",tr:"/ˈsɜːveɪ/",uz:"kuzatuv"},
{en:"sweetcorn",tr:"/ˈswiːtkɔːn/",uz:"shirin jo'hori"},{en:"take away food",tr:"/ˈteɪkəweɪfuːd/",uz:"o'zi bilan olib ketiladigan ovqat"},
{en:"unhealthy",tr:"/ˌʌnˈhelθi/",uz:"sog'liqqa zararli"},{en:"vegetable",tr:"/ˈvedʒtəbl/",uz:"sabzavot"},
{en:"view",tr:"/vjuː/",uz:"manzara, ko'rinish"},{en:"wonderful",tr:"/ˈwʌndəfl/",uz:"ajoyib"},
{en:"yoghurt",tr:"/ˈjɒɡət/",uz:"qatiq"}
]},
{id:'u10',name:'Elementary Unit 10',words:[
{en:"accent",tr:"/ˈæksent/",uz:"talaffuz, ohang"},{en:"blow",tr:"/bləʊ/",uz:"esmoq"},
{en:"busy",tr:"/ˈbɪzi/",uz:"gavjum"},{en:"camp",tr:"/kæmp/",uz:"lager, oromgoh"},
{en:"climate",tr:"/ˈklaɪmət/",uz:"iqlim"},{en:"close",tr:"/kləʊs/",uz:"yaqin"},
{en:"cloudy",tr:"/ˈklaʊdi/",uz:"bulutli"},{en:"coast",tr:"/kəʊst/",uz:"sohil, qirg'oq"},
{en:"compass",tr:"/ˈkʌmpəs/",uz:"kompas"},{en:"crazy",tr:"/ˈkreɪzi/",uz:"telba; aqldan ozgan"},
{en:"deep",tr:"/diːp/",uz:"chuqur"},{en:"desert",tr:"/ˈdezət/",uz:"cho'l"},
{en:"dry",tr:"/draɪ/",uz:"quruq"},{en:"east",tr:"/iːst/",uz:"sharq"},
{en:"equipment",tr:"/ɪˈkwɪpmənt/",uz:"jihoz, uskuna"},{en:"first-aid kit",tr:"/fɜːstˈeɪdkɪt/",uz:"birinchi yordam anjomlari"},
{en:"foggy",tr:"/ˈfɒɡi/",uz:"tumanli"},{en:"freeze",tr:"/friːz/",uz:"muzlab qolmoq"},
{en:"freezing",tr:"/ˈfriːzɪŋ/",uz:"qahraton sovuq"},{en:"hard worker",tr:"/hɑːdˈwɜːkə(r)/",uz:"mehnatkash"},
{en:"high",tr:"/haɪ/",uz:"baland"},{en:"hot",tr:"/hɒt/",uz:"issiq"},
{en:"icy",tr:"/ˈaɪsi/",uz:"muzlagan"},{en:"island",tr:"/ˈaɪlənd/",uz:"orol"},
{en:"jungle",tr:"/ˈdʒʌŋɡl/",uz:"chakalakzor"},{en:"lake",tr:"/leɪk/",uz:"ko'l"},
{en:"large",tr:"/lɑːdʒ/",uz:"katta, yirik"},{en:"lighter",tr:"/ˈlaɪtə(r)/",uz:"zajigalka, yoritgich"},
{en:"low",tr:"/ləʊ/",uz:"kam, past"},{en:"mild",tr:"/maɪld/",uz:"yumshoq, mayin"},
{en:"north",tr:"/nɔːθ/",uz:"shimol"},{en:"oasis",tr:"/əʊˈeɪsɪs/",uz:"voha"},
{en:"rain",tr:"/reɪn/",uz:"yomg'ir"},{en:"rainy",tr:"/ˈreɪni/",uz:"yomg'irli"},
{en:"river",tr:"/ˈrɪvə(r)/",uz:"daryo"},{en:"sandy",tr:"/ˈsændi/",uz:"qumli"},
{en:"score",tr:"/skɔː(r)/",uz:"natija, baho"},{en:"shine",tr:"/ʃaɪn/",uz:"nur sochmoq, yoritmoq"},
{en:"sleeper",tr:"/ˈsliːpə(r)/",uz:"uyquchi"},{en:"snow",tr:"/snəʊ/",uz:"qor"},
{en:"snowy",tr:"/ˈsnəʊi/",uz:"qorli"},{en:"south",tr:"/saʊθ/",uz:"janub"},
{en:"storm",tr:"/stɔːm/",uz:"to'fon; dovul"},{en:"stove",tr:"/stəʊv/",uz:"oshxona plitasi"},
{en:"sunny",tr:"/ˈsʌni/",uz:"quyoshli"},{en:"survival",tr:"/səˈvaɪvl/",uz:"tirik qolish"},
{en:"survive",tr:"/səˈvaɪv/",uz:"tirik qolmoq"},{en:"tent",tr:"/tent/",uz:"chodir, palatka"},
{en:"temperature",tr:"/ˈtemprətʃə(r)/",uz:"harorat"},{en:"thunder",tr:"/ˈθʌndə(r)/",uz:"momoqaldiroq, chaqmoq"},
{en:"torch",tr:"/tɔːtʃ/",uz:"fonar, mash'al"},{en:"traffic",tr:"/ˈtræfɪk/",uz:"yo'l-transport harakati"},
{en:"tropical",tr:"/ˈtrɒpɪkl/",uz:"tropik"},{en:"warm",tr:"/wɔːm/",uz:"iliq"},
{en:"waterfall",tr:"/ˈwɔːtəfɔːl/",uz:"sharshara"},{en:"weather",tr:"/ˈweðə(r)/",uz:"ob-havo"},
{en:"weather forecast",tr:"/ˈweðəˌfɔːkɑːst/",uz:"ob-havo ma'lumoti"},{en:"west",tr:"/west/",uz:"g'arb"},
{en:"wet",tr:"/wet/",uz:"nam"},{en:"windy",tr:"/ˈwɪndi/",uz:"shamolli"},
{en:"worker",tr:"/ˈwɜːkə(r)/",uz:"ishchi"}
]},
{id:'u11',name:'Elementary Unit 11',words:[
{en:"annually",tr:"/ˈænjuəli/",uz:"har yili"},{en:"award",tr:"/əˈwɔːd/",uz:"mukofotlamoq"},
{en:"awful",tr:"/ˈɔːfl/",uz:"juda yomon"},{en:"bark",tr:"/bɑːk/",uz:"vovullamoq"},
{en:"brilliant",tr:"/ˈbrɪlɪənt/",uz:"juda zo'r, aqlli"},{en:"celebrate",tr:"/ˈselɪbreɪt/",uz:"nishonlamoq"},
{en:"charity",tr:"/ˈtʃærəti/",uz:"xayriya"},{en:"coach",tr:"/kəʊtʃ/",uz:"murabbiy"},
{en:"common",tr:"/ˈkɒmən/",uz:"oddiy, odatiy"},{en:"community",tr:"/kəˈmjuːnəti/",uz:"jamoat, mahalla"},
{en:"constantly",tr:"/ˈkɒnstəntli/",uz:"uzluksiz, doimiy"},{en:"crucial",tr:"/ˈkruːʃl/",uz:"muhim, asosiy"},
{en:"delighted",tr:"/dɪˈlaɪtɪd/",uz:"xursand"},{en:"dietician",tr:"/ˌdaɪəˈtɪʃn/",uz:"diyetolog"},
{en:"elderly",tr:"/ˈeldəli/",uz:"qari, keksa"},{en:"excellent",tr:"/ˈeksələnt/",uz:"a'lo; zo'r"},
{en:"fail",tr:"/feɪl/",uz:"yiqilmoq, uddalay olmaslik"},{en:"focus",tr:"/ˈfəʊkəs/",uz:"diqqatni qaratmoq"},
{en:"help",tr:"/help/",uz:"yordam bermoq"},{en:"homeless",tr:"/ˈhəʊmləs/",uz:"uysiz, boshpanasiz"},
{en:"huge",tr:"/hjuːdʒ/",uz:"ulkan"},{en:"improve",tr:"/ɪmˈpruːv/",uz:"yaxshilamoq"},
{en:"individual",tr:"/ˌɪndɪˈvɪdʒuəl/",uz:"individual; har bir shaxs"},{en:"look after",tr:"/lʊkˈɑːftə(r)/",uz:"g'amxo'rlik qilmoq"},
{en:"lovely",tr:"/ˈlʌvli/",uz:"ajoyib"},{en:"massive",tr:"/ˈmæsɪv/",uz:"juda katta"},
{en:"maximum",tr:"/ˈmæksɪməm/",uz:"maksimum, eng ko'pi bilan"},{en:"member",tr:"/ˈmembə(r)/",uz:"a'zo"},
{en:"organize",tr:"/ˈɔːɡənaɪz/",uz:"tashkillashtirmoq"},{en:"paint",tr:"/peɪnt/",uz:"bo'yamoq"},
{en:"plant",tr:"/plɑːnt/",uz:"ekmoq"},{en:"repair",tr:"/rɪˈpeə(r)/",uz:"tuzatmoq"},
{en:"player",tr:"/ˈpleɪə(r)/",uz:"o'yinchi"},{en:"resident",tr:"/ˈrezɪdənt/",uz:"yashovchi"},
{en:"scared",tr:"/skeəd/",uz:"qo'rqqan"},{en:"soil",tr:"/sɔɪl/",uz:"tuproq, yer"},
{en:"tax",tr:"/tæks/",uz:"soliq"},{en:"teach",tr:"/tiːtʃ/",uz:"o'qitmoq, o'rgatmoq"},
{en:"team",tr:"/tiːm/",uz:"jamoa"},{en:"tiny",tr:"/ˈtaɪmi/",uz:"mayda"},
{en:"worried",tr:"/ˈwʌrɪd/",uz:"xavotirlangan"}
]},
{id:'u12',name:'Elementary Unit 12',words:[
{en:"acrobat",tr:"/ˈækrəbæt/",uz:"akrobat"},{en:"action film",tr:"/ˈækʃnfɪlm/",uz:"jangari film"},
{en:"album",tr:"/ˈælbəm/",uz:"albom"},{en:"animation",tr:"/ˌænɪˈmeɪʃn/",uz:"multfilm"},
{en:"autistic",tr:"/ɔːˈtɪstɪk/",uz:"autistik"},{en:"band",tr:"/bænd/",uz:"guruh"},
{en:"black and white",tr:"/ˌblækən ˈwaɪt/",uz:"oq-qora"},{en:"blind",tr:"/blaɪnd/",uz:"ko'r, ojiz"},
{en:"circus",tr:"/ˈsɜːkəs/",uz:"sirk"},{en:"clap",tr:"/klæp/",uz:"qarsak chalmoq"},
{en:"collection",tr:"/kəˈlekʃn/",uz:"to'plam"},{en:"comedy",tr:"/ˈkɒmədi/",uz:"komediya"},
{en:"concert",tr:"/ˈkɒnsɪt/",uz:"konsert"},{en:"deaf",tr:"/def/",uz:"kar"},
{en:"drama",tr:"/ˈdrɑːmə/",uz:"drama"},{en:"drum",tr:"/drʌm/",uz:"baraban"},
{en:"experience",tr:"/ɪkˈspɪərɪəns/",uz:"tajriba"},{en:"favourite",tr:"/ˈfeɪvərɪt/",uz:"sevimli"},
{en:"future",tr:"/ˈfjuːtʃə(r)/",uz:"kelajak"},{en:"gallery",tr:"/ˈɡæləri/",uz:"galereya"},
{en:"hang on",tr:"/ˈhæŋɒn/",uz:"kutib turmoq"},{en:"helicopter",tr:"/ˈhelɪkɒptə(r)/",uz:"vertolyot"},
{en:"horror film",tr:"/ˈhɒrəfɪlm/",uz:"dahshatli film"},{en:"illness",tr:"/ˈɪlnəs/",uz:"kasallik"},
{en:"independence",tr:"/ˌɪndɪˈpendəns/",uz:"mustaqillik"},{en:"instrument",tr:"/ˈɪnstrəmənt/",uz:"uskuna, asbob"},
{en:"lesson",tr:"/ˈlesn/",uz:"dars"},{en:"love story",tr:"/ˈlʌvˌstɔːri/",uz:"sevgi hikoyasi"},
{en:"musical",tr:"/ˈmjuːzɪkl/",uz:"musiqiy"},{en:"music festival",tr:"/ˈmjuːzɪk ˌfestɪvl/",uz:"musiqiy festival"},
{en:"opera",tr:"/ˈɒprə/",uz:"opera"},{en:"play",tr:"/pleɪ/",uz:"o'yin"},
{en:"painting lesson",tr:"/ˈpeɪntɪŋ ˌlesn/",uz:"rasm darsi"},{en:"prefer",tr:"/prɪˈfɜː(r)/",uz:"afzal ko'rmoq"},
{en:"prize",tr:"/praɪz/",uz:"mukofot"},{en:"romantic film",tr:"/rəʊˈmæntɪk tɪkfɪlm/",uz:"romantik film"},
{en:"scary",tr:"/ˈskeəri/",uz:"qo'rqinchli"},{en:"science fiction film",tr:"/ˈsaɪəns ˈfɪkʃnfɪlm/",uz:"ilmiy fantastik film"},
{en:"stage",tr:"/steɪdʒ/",uz:"sahna"},{en:"star",tr:"/stɑː(r)/",uz:"bosh rolni bermoq"},
{en:"surprise",tr:"/səˈpraɪz/",uz:"kutilmagan sovg'a, xabar"}
]}
];
;


/* --- Irregular Verbs Ma'lumotlari --- */
const IRREGULAR_VERBS = [{"base": "be", "past": "was/were", "pp": "been", "uz": "bo'lmoq", "emoji": "🧍"}, {"base": "go", "past": "went", "pp": "gone", "uz": "bormoq", "emoji": "🚶"}, {"base": "come", "past": "came", "pp": "come", "uz": "kelmoq", "emoji": "🏃"}, {"base": "see", "past": "saw", "pp": "seen", "uz": "ko'rmoq", "emoji": "👀"}, {"base": "eat", "past": "ate", "pp": "eaten", "uz": "yemoq", "emoji": "🍽️"}, {"base": "drink", "past": "drank", "pp": "drunk", "uz": "ichmoq", "emoji": "🥤"}, {"base": "have", "past": "had", "pp": "had", "uz": "egalik qilmoq", "emoji": "🤲"}, {"base": "do", "past": "did", "pp": "done", "uz": "qilmoq", "emoji": "✅"}, {"base": "make", "past": "made", "pp": "made", "uz": "yasamoq", "emoji": "🔨"}, {"base": "take", "past": "took", "pp": "taken", "uz": "olmoq", "emoji": "✋"}, {"base": "give", "past": "gave", "pp": "given", "uz": "bermoq", "emoji": "🎁"}, {"base": "get", "past": "got", "pp": "got", "uz": "olmoq, qabul qilmoq", "emoji": "📦"}, {"base": "say", "past": "said", "pp": "said", "uz": "aytmoq", "emoji": "💬"}, {"base": "tell", "past": "told", "pp": "told", "uz": "aytib bermoq", "emoji": "🗣️"}, {"base": "think", "past": "thought", "pp": "thought", "uz": "o'ylamoq", "emoji": "🤔"}, {"base": "know", "past": "knew", "pp": "known", "uz": "bilmoq", "emoji": "💡"}, {"base": "find", "past": "found", "pp": "found", "uz": "topmoq", "emoji": "🔍"}, {"base": "feel", "past": "felt", "pp": "felt", "uz": "his qilmoq", "emoji": "❤️"}, {"base": "become", "past": "became", "pp": "become", "uz": "aylanmoq, bo'lmoq", "emoji": "🦋"}, {"base": "leave", "past": "left", "pp": "left", "uz": "ketmoq, qoldirmoq", "emoji": "🚪"}, {"base": "put", "past": "put", "pp": "put", "uz": "qo'ymoq", "emoji": "📥"}, {"base": "bring", "past": "brought", "pp": "brought", "uz": "olib kelmoq", "emoji": "🎒"}, {"base": "buy", "past": "bought", "pp": "bought", "uz": "sotib olmoq", "emoji": "🛍️"}, {"base": "begin", "past": "began", "pp": "begun", "uz": "boshlamoq", "emoji": "🏁"}, {"base": "write", "past": "wrote", "pp": "written", "uz": "yozmoq", "emoji": "✍️"}, {"base": "read", "past": "read", "pp": "read", "uz": "o'qimoq", "emoji": "📖"}, {"base": "run", "past": "ran", "pp": "run", "uz": "yugurmoq", "emoji": "🏃‍♂️"}, {"base": "speak", "past": "spoke", "pp": "spoken", "uz": "gapirmoq", "emoji": "🗨️"}, {"base": "sit", "past": "sat", "pp": "sat", "uz": "o'tirmoq", "emoji": "🪑"}, {"base": "stand", "past": "stood", "pp": "stood", "uz": "turmoq", "emoji": "🧍‍♂️"}, {"base": "sleep", "past": "slept", "pp": "slept", "uz": "uxlamoq", "emoji": "😴"}, {"base": "wake", "past": "woke", "pp": "woken", "uz": "uyg'onmoq", "emoji": "⏰"}, {"base": "fly", "past": "flew", "pp": "flown", "uz": "uchmoq", "emoji": "✈️"}, {"base": "drive", "past": "drove", "pp": "driven", "uz": "haydamoq", "emoji": "🚗"}, {"base": "ride", "past": "rode", "pp": "ridden", "uz": "minib yurmoq", "emoji": "🚲"}, {"base": "swim", "past": "swam", "pp": "swum", "uz": "suzmoq", "emoji": "🏊"}, {"base": "win", "past": "won", "pp": "won", "uz": "g'alaba qilmoq", "emoji": "🏆"}, {"base": "lose", "past": "lost", "pp": "lost", "uz": "yo'qotmoq", "emoji": "😢"}, {"base": "break", "past": "broke", "pp": "broken", "uz": "sindirmoq", "emoji": "💔"}, {"base": "build", "past": "built", "pp": "built", "uz": "qurmoq", "emoji": "🏗️"}, {"base": "buy", "past": "bought", "pp": "bought", "uz": "sotib olmoq", "emoji": "💰"}, {"base": "catch", "past": "caught", "pp": "caught", "uz": "ushlamoq", "emoji": "🥎"}, {"base": "choose", "past": "chose", "pp": "chosen", "uz": "tanlamoq", "emoji": "☑️"}, {"base": "cut", "past": "cut", "pp": "cut", "uz": "kesmoq", "emoji": "✂️"}, {"base": "draw", "past": "drew", "pp": "drawn", "uz": "chizmoq", "emoji": "🎨"}, {"base": "drop", "past": "dropped", "pp": "dropped", "uz": "tushirmoq", "emoji": "⬇️"}, {"base": "fall", "past": "fell", "pp": "fallen", "uz": "yiqilmoq", "emoji": "🍂"}, {"base": "feed", "past": "fed", "pp": "fed", "uz": "ovqatlantirmoq", "emoji": "🍼"}, {"base": "fight", "past": "fought", "pp": "fought", "uz": "jang qilmoq", "emoji": "⚔️"}, {"base": "forget", "past": "forgot", "pp": "forgotten", "uz": "unutmoq", "emoji": "🤷"}, {"base": "grow", "past": "grew", "pp": "grown", "uz": "o'smoq", "emoji": "🌱"}, {"base": "hear", "past": "heard", "pp": "heard", "uz": "eshitmoq", "emoji": "👂"}, {"base": "hide", "past": "hid", "pp": "hidden", "uz": "yashirmoq", "emoji": "🙈"}, {"base": "hold", "past": "held", "pp": "held", "uz": "ushlab turmoq", "emoji": "🤝"}, {"base": "hurt", "past": "hurt", "pp": "hurt", "uz": "jarohatlanmoq", "emoji": "🤕"}, {"base": "keep", "past": "kept", "pp": "kept", "uz": "saqlamoq", "emoji": "🔒"}, {"base": "meet", "past": "met", "pp": "met", "uz": "uchrashmoq", "emoji": "🤝"}, {"base": "pay", "past": "paid", "pp": "paid", "uz": "to'lamoq", "emoji": "💵"}, {"base": "send", "past": "sent", "pp": "sent", "uz": "yubormoq", "emoji": "📤"}, {"base": "show", "past": "showed", "pp": "shown", "uz": "ko'rsatmoq", "emoji": "👉"}, {"base": "sing", "past": "sang", "pp": "sung", "uz": "qo'shiq aytmoq", "emoji": "🎤"}, {"base": "steal", "past": "stole", "pp": "stolen", "uz": "o'g'irlamoq", "emoji": "🥷"}, {"base": "teach", "past": "taught", "pp": "taught", "uz": "o'qitmoq", "emoji": "👩‍🏫"}, {"base": "throw", "past": "threw", "pp": "thrown", "uz": "tashlamoq", "emoji": "🤾"}, {"base": "understand", "past": "understood", "pp": "understood", "uz": "tushunmoq", "emoji": "🧠"}, {"base": "wear", "past": "wore", "pp": "worn", "uz": "kiymoq", "emoji": "👕"}];

